version: '3.8'

services:
  strapi:
    image: strapi/strapi
    container_name: strapi_mariadb
    environment:
      # Altough Database client (DBMS) being used is MariaDB, according to Strapi docs, the value is 'mysql'. For more: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#database
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_NAME: ${DATABASE_NAME:-strapidb}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapidb_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-P@ssw0rd}
      DATABASE_SSL: ${DATABASE_SSL:-false}
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-r00tP@ssw0rd}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-strapidb}
      MARIADB_USER: ${MARIADB_USER:-strapidb_user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-P@ssw0rd}
